import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";

export function TermsPage() {
	return(
		<>
			<div className="container-fluid" style={{marginTop: '50px'}}>	
				<Header height="150px"/>
				<div style={{padding: '50px 190px'}}>
					<h2>Terms of Service</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rutrum pharetra fringilla. Etiam nec turpis eu lorem maximus condimentum vitae nec nibh. Morbi tempor, risus ac congue gravida, ligula sapien lobortis leo, a condimentum lectus est eget sem. Cras eu suscipit lectus, vitae pulvinar mi. Curabitur turpis neque, aliquet pharetra urna in, tempus pretium est. Sed placerat velit eu ipsum molestie mollis. Maecenas rutrum suscipit diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam odio vitae vulputate sollicitudin</p>
					<p>Aliquam a eleifend lacus. Vestibulum velit orci, lobortis sed nunc sed, auctor pharetra orci. Vivamus accumsan ornare ante sit amet venenatis. Etiam convallis magna et lorem sagittis efficitur. Donec fermentum sed tellus tristique tempus. Praesent a sem id eros porttitor hendrerit. Nullam sed tempus metus. Suspendisse hendrerit non magna in tincidunt. Nam consequat sem eu justo laoreet eleifend. Fusce id urna magna. Pellentesque finibus enim nec pulvinar pellentesque. Mauris iaculis aliquet ante ac suscipit. Sed vitae gravida erat. In bibendum elit quis dui cursus malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nunc vitae eros blandit suscipit a ut nibh.</p>
					<p>Duis fringilla ex vitae lacus laoreet, a sodales augue porttitor. Nam commodo orci eu tempus tempus. Sed pellentesque orci vel lectus gravida tempus. Quisque pellentesque molestie velit, nec aliquam neque consectetur ac. Donec sodales quam nec ex ornare bibendum. Aliquam eu velit sem. Quisque posuere nisi eget diam cursus iaculis. Curabitur sit amet consequat sapien. Donec vitae luctus metus, vitae tempor nunc. Nunc vel nunc nulla. Sed porta erat eget lectus tincidunt, a blandit eros vulputate. Vestibulum lobortis porttitor velit, eget placerat purus. Pellentesque sed nisl accumsan nulla gravida ornare.</p>
					<p>Aliquam eget lacus posuere, mollis leo at, pulvinar augue. Donec rutrum pharetra urna nec porta. Suspendisse consectetur eleifend mi. Morbi tincidunt sapien ante, quis scelerisque odio consectetur gravida. Donec aliquet mattis sodales. Sed facilisis vulputate eros ullamcorper aliquet. Vestibulum semper purus ligula, sed venenatis nibh malesuada vel. Sed vehicula eros id nibh lobortis tincidunt. Donec non ullamcorper nulla, et ultricies orci. Donec congue finibus condimentum. Nulla nec nisl vitae ante consectetur tristique. Vestibulum condimentum tortor lacinia ipsum vestibulum, accumsan facilisis lorem blandit.</p>
					<p>Nam sed lectus laoreet, euismod odio vel, egestas tortor. Maecenas hendrerit ipsum non nisl tristique, sit amet imperdiet tellus pretium. Integer porttitor mauris nisl. Proin sit amet purus vitae enim volutpat elementum id sit amet dui. Duis ac velit efficitur, venenatis lectus eget, convallis velit. Fusce non interdum arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a lectus arcu. Etiam sed semper nisl, sed molestie ex. Nullam a vestibulum erat, faucibus lacinia sapien. Praesent id ex at urna dictum maximus in nec nisl.</p>
					<p>Duis fringilla ex vitae lacus laoreet, a sodales augue porttitor. Nam commodo orci eu tempus tempus. Sed pellentesque orci vel lectus gravida tempus. Quisque pellentesque molestie velit, nec aliquam neque consectetur ac. Donec sodales quam nec ex ornare bibendum. Aliquam eu velit sem. Quisque posuere nisi eget diam cursus iaculis. Curabitur sit amet consequat sapien. Donec vitae luctus metus, vitae tempor nunc. Nunc vel nunc nulla. Sed porta erat eget lectus tincidunt, a blandit eros vulputate. Vestibulum lobortis porttitor velit, eget placerat purus. Pellentesque sed nisl accumsan nulla gravida ornare.</p>
					<p>Duis fringilla ex vitae lacus laoreet, a sodales augue porttitor. Nam commodo orci eu tempus tempus. Sed pellentesque orci vel lectus gravida tempus. Quisque pellentesque molestie velit, nec aliquam neque consectetur ac. Donec sodales quam nec ex ornare bibendum. Aliquam eu velit sem. Quisque posuere nisi eget diam cursus iaculis. Curabitur sit amet consequat sapien. Donec vitae luctus metus, vitae tempor nunc. Nunc vel nunc nulla. Sed porta erat eget lectus tincidunt, a blandit eros vulputate. Vestibulum lobortis porttitor velit, eget placerat purus. Pellentesque sed nisl accumsan nulla gravida ornare.</p>
				</div>
				<Footer/>
			</div>
		</>
	)
}